import{a as k,S as p,i as n}from"./assets/vendor-95dc692e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();async function m(t,o){const a="https://pixabay.com/api/";return(await k.get(a,{params:{key:"43047953-84179c8300fd9f33658a206cf",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15}})).data}const f=document.querySelector(".back-to-top"),q=document.querySelector(".gallery");function T(){f.classList.remove("is-hidden")}function M(){f.classList.add("is-hidden")}function h(t){if(t.length==0)M(),n.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{T();const o=t.map(r=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img class="photo" src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");q.insertAdjacentHTML("beforeend",o),new p(".gallery a",{captionsData:"alt"}).refresh()}}const R=new p(".gallery a",{});R.refresh();const v=document.querySelector(".back-to-top"),g=document.querySelector(".gallery"),E=document.querySelector("form"),y=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");let i=1,c,d,F=15;function L(){y.classList.remove("is-hidden")}function b(){y.classList.add("is-hidden")}function P(){u.classList.remove("is-hidden")}function w(){u.classList.add("is-hidden")}function S(){i>=d?w():P()}function $(){const t=g.firstElementChild.getBoundingClientRect().height;scrollBy({top:t,behavior:"smooth"})}E.addEventListener("submit",x);u.addEventListener("click",B);async function x(t){if(t.preventDefault(),c=t.target.elements.query.value.trim(),g.innerHTML="",i=1,!c){n.error({color:"yellow",message:" Please fill in the field for search",position:"topRight"});return}try{L();const o=await m(c,i);d=Math.ceil(o.totalHits/F),h(o.hits)}catch(o){console.log(o),n.error({title:"Error",message:"❌ Sorry, error occurred. Please, try again!",position:"topRight"})}b(),S(),t.target.reset()}async function B(){i+=1,L();try{const t=await m(c,i);if(h(t.hits),i>=d){w();const o='<p class="thank-you-text">Thank you for <br> using our website!</p>';v.insertAdjacentHTML("beforeend",o),n.warning({title:"End of collection",color:"blue",message:" Sorry, there are no more images matching your query ",position:"topRight"})}}catch(t){console.log(t),n.error({title:"Error",message:"❌ Sorry, error occurred",position:"topRight"})}$(),S(),b()}
//# sourceMappingURL=commonHelpers.js.map
