import{a as w,S as u,i as c}from"./assets/vendor-95dc692e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();async function p(t,o){const n="https://pixabay.com/api/";return(await w.get(n,{params:{key:"43047953-84179c8300fd9f33658a206cf",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15}})).data}const S=document.querySelector(".back-to-top"),q=document.querySelector(".gallery");function m(t){if(t.length==0)c.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),S.classList.add("is-hidden");else{const o=t.map(r=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img class="photo" src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");q.insertAdjacentHTML("beforeend",o),new u(".gallery a",{captionsData:"alt"}).refresh()}}const k=new u(".gallery a",{});k.refresh();const f=document.querySelector(".gallery"),v=document.querySelector("form"),h=document.querySelector(".loader"),d=document.querySelector(".load-more-btn"),F=document.querySelector(".back-to-top");let i=1,a,g,M=15;function y(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function P(){d.classList.remove("is-hidden")}function R(){d.classList.add("is-hidden")}function b(){i>=g?R():P()}function T(){const t=f.firstElementChild.getBoundingClientRect().height;scrollBy({top:t,behavior:"smooth"})}function $(){F.classList.remove("is-hidden")}v.addEventListener("submit",E);d.addEventListener("click",x);async function E(t){if(t.preventDefault(),a=t.target.elements.query.value.trim(),f.innerHTML="",i=1,!a){c.error({color:"yellow",message:" Please fill in the field for search",position:"topRight"});return}try{y();const o=await p(a,i);g=Math.ceil(o.totalHits/M),m(o.hits),$()}catch(o){console.log(o),c.error({title:"Error",message:"❌ Sorry, error occurred. Please, try again!",position:"topRight"})}L(),b(),t.target.reset()}async function x(){i+=1,y();try{const t=await p(a,i);m(t.hits)}catch(t){console.log(t),c.error({title:"Error",message:"❌ Sorry, error occurred",position:"topRight"})}T(),b(),L()}
//# sourceMappingURL=commonHelpers.js.map
